In [14]:
import numpy as np

#normalization
#nomralized value= (datapoint-mean)/standardDeviation
a = np.array([1,2,3,4,50,30,45,68,75,9,0,-100,500,650,75])

In [15]:
from sklearn.preprocessing import scale
d=scale(a)
d

array([-0.477348  , -0.47222257, -0.46709715, -0.46197172, -0.22620213,
       -0.32871065, -0.25182926, -0.13394446, -0.09806648, -0.43634459,
       -0.48247342, -0.99501601,  2.08023952,  2.84905341, -0.09806648])

In [16]:
b=a.mean()
c=a.std()

[((i-b)/c) for i in a ]

[-0.477347998191104,
 -0.4722225722978567,
 -0.4670971464046093,
 -0.461971720511362,
 -0.22620212942198345,
 -0.3287106472869306,
 -0.2518292588882203,
 -0.133944463343531,
 -0.09806648209079949,
 -0.4363445910451252,
 -0.4824734240843514,
 -0.9950160134090872,
 2.080239522539328,
 2.8490534065264317,
 -0.09806648209079949]

In [17]:
d.mean()

-5.921189464667501e-17

In [18]:
d.std()

1.0

In [7]:
#lizol, dhoodh, ghee, dhaniya powder, dishsoap, chhole, rajma, tamater, dalchini, laung, khada lal mirch, heeng,

In [21]:
from sklearn.preprocessing import MinMaxScaler
default_scaler=MinMaxScaler()
transformed=default_scaler.fit_transform([a])
transformed

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
#RobustScaling outlier prevention
from sklearn.preprocessing import RobustScaler
rs=RobustScaler()
transformed=rs.fit_transform([a])
print(transformed)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [24]:
#L2 normalization
from sklearn.preprocessing import Normalizer
n=Normalizer()
n_data=n.fit_transform([a])
n_data

array([[ 0.0011919 ,  0.00238381,  0.00357571,  0.00476762,  0.05959522,
         0.03575713,  0.0536357 ,  0.0810495 ,  0.08939283,  0.01072714,
         0.        , -0.11919044,  0.59595221,  0.77473788,  0.08939283]])

In [28]:
#nan values with sklearn
data=np.array([1,2,3,4,45,56,np.nan,13,14,15,16,np.nan])
from sklearn.impute import SimpleImputer
imp_mean=SimpleImputer(strategy='median')
transformed=imp_mean.fit_transform([data])
transformed

array([[ 1.,  2.,  3.,  4., 45., 56., 13., 14., 15., 16.]])

In [ ]:
#pca
from sklearn.decomposition import PCA
pc = PCA.fit_transform(data).round(3)

In [29]:
from sklearn.datasets import load_breast_cancer
bc=load_breast_cancer()
print(repr(bc))

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [30]:
bc.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [32]:
bc.data.shape

(569, 30)

In [33]:
bc.target.shape

(569,)

In [34]:
bc.target_names

array(['malignant', 'benign'], dtype='<U9')