In [2]:
import numpy as np
a=np.arange(0,15,1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
a.ndim

1

In [4]:
a.shape

(15,)

In [5]:
a.size

15

In [6]:
a.dtype

dtype('int64')

In [7]:
a.itemsize

8

In [10]:
np.reshape(a,(5,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [11]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.amin(a)

0

In [13]:
np.amax(a)

14

In [16]:
np.sum(a,axis=0)

105

In [19]:
np.cumsum(a,axis=0)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105])

In [20]:
np.ravel(a,order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
a.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [27]:
np.empty((3,3))

array([[1.01855798e-312, 1.01855798e-312, 1.01855798e-312],
       [1.01855798e-312, 6.79038653e-313, 9.76118064e-313],
       [1.01855798e-312, 1.01855798e-312, 1.01855798e-312]])

In [34]:
np.eye((3),k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
np.linspace(0,9,18)

array([0.        , 0.52941176, 1.05882353, 1.58823529, 2.11764706,
       2.64705882, 3.17647059, 3.70588235, 4.23529412, 4.76470588,
       5.29411765, 5.82352941, 6.35294118, 6.88235294, 7.41176471,
       7.94117647, 8.47058824, 9.        ])

In [39]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [42]:
np.array_split(a,2)

[array([0, 1, 2, 3, 4, 5, 6, 7]), array([ 8,  9, 10, 11, 12, 13, 14])]

In [46]:
b=np.arange(20,35,1)

In [47]:
np.column_stack((a,b))

array([[ 0, 20],
       [ 1, 21],
       [ 2, 22],
       [ 3, 23],
       [ 4, 24],
       [ 5, 25],
       [ 6, 26],
       [ 7, 27],
       [ 8, 28],
       [ 9, 29],
       [10, 30],
       [11, 31],
       [12, 32],
       [13, 33],
       [14, 34]])

In [50]:
np.concatenate((a,b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [52]:
np.hsplit(a,3)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

In [55]:
c=b.reshape((3,5))

In [58]:
np.vsplit(c,3)

[array([[20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34]])]

In [60]:
np.hstack((a,b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [64]:
d=np.vstack((a,b))
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]])

In [65]:
np.squeeze(d) #Read more about it

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]])

In [70]:
np.argmax(d)

29

In [71]:
np.argmin(d)

0

In [73]:
np.sort(d,axis=1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]])

In [74]:
np.mean(a)

7.0

In [75]:
np.std(a)

4.320493798938574

In [76]:
np.var(a)

18.666666666666668

In [77]:
a*b

array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261, 300, 341, 384,
       429, 476])

In [78]:
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [79]:
print(repr(a))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


In [80]:
'''
Similar to Python lists, when we make a reference to a NumPy array it doesn't create a different array. Therefore, if we change a value using the reference variable, it changes the original array as well. We get around this by using an array's inherent copy function. The function has no required arguments, and it returns the copied array.

'''

"\nSimilar to Python lists, when we make a reference to a NumPy array it doesn't create a different array. Therefore, if we change a value using the reference variable, it changes the original array as well. We get around this by using an array's inherent copy function. The function has no required arguments, and it returns the copied array.\n\n"

In [82]:
f = a.copy()
f[0]=10
print(a)
print(f)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[10  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [84]:
g=a.astype(np.float64)
g

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [86]:
arr = np.array([np.nan,1,2])
print(repr(arr))
#np.nan can't be initialize with type int but only float64

array([nan,  1.,  2.])


In [88]:
np.inf>1000

True

In [89]:
-np.inf>100

False

In [90]:
arr = np.array([np.nan,2,3,4,5])
arr2=arr.copy()
arr2[0]=10


In [92]:
float_arr=np.array([1,5.4,3],dtype=float)
float_arr2=float_arr.astype(np.float32)
repr(float_arr2)

'array([1. , 5.4, 3. ], dtype=float32)'

In [93]:
matrix=np.array([[1,2,3],[4,5,6]],dtype=np.float32)

In [94]:
matrix

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [95]:
np.transpose(matrix)

array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)

In [97]:
np.reshape(matrix,(3,2))

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)

In [98]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06])

In [99]:
np.log(a)

/var/folders/3x/bz536h6929q9kwynkd0t0mzh0000gn/T/ipykernel_835/176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733])

In [100]:
np.log2(a)

/var/folders/3x/bz536h6929q9kwynkd0t0mzh0000gn/T/ipykernel_835/2088242240.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(a)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ,
       3.32192809, 3.45943162, 3.5849625 , 3.70043972, 3.80735492])

In [101]:
np.log10(a)

/var/folders/3x/bz536h6929q9kwynkd0t0mzh0000gn/T/ipykernel_835/547625357.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251,
       1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804])

In [102]:
np.power(a,2)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [103]:
np.matmul(a,b) #dot matrix multiplication

3115

In [104]:
np.random.randint(3,10,size=(4,4))

array([[9, 5, 5, 6],
       [4, 6, 9, 4],
       [5, 7, 7, 5],
       [3, 4, 5, 7]])

In [112]:
np.random.seed(1)
np.random.randint(0,10,size=(5,5))

array([[5, 8, 9, 5, 0],
       [0, 1, 7, 6, 9],
       [2, 4, 5, 2, 4],
       [2, 4, 7, 7, 9],
       [1, 7, 0, 6, 9]])

In [118]:
np.random.shuffle(a)
a

array([ 4,  5, 12,  1,  9,  6, 10,  3,  2,  0,  8, 14, 13,  7, 11])

In [119]:
np.random.uniform(1,100,size=(10,10))

array([[40.37000686, 17.37006551, 92.82334946, 35.42882011, 75.33039821,
        72.87380055, 88.44730303, 62.7435485 , 75.34330097, 35.54093586],
       [27.72286128, 89.6927356 , 43.3810278 , 96.51916467, 66.68070828,
        62.5478763 , 12.35985132, 94.99943661, 45.54130121, 58.26057182],
       [41.40554347, 24.46567104, 90.43457254, 57.79426918,  1.28416238,
        62.09734645, 33.33784528, 53.17875212, 88.70826783, 36.36970624],
       [90.94497994, 62.71265146,  2.56630304, 93.01428614, 69.39879483,
        99.73496219, 18.06171033, 14.57643921, 93.32695084, 69.98499799],
       [ 7.5340171 , 75.79084221, 75.63374266, 92.37942902, 71.4409511 ,
        13.30282524,  2.96813325,  3.5948877 ,  3.80234231, 25.37489569],
       [86.14276692, 54.34427537, 55.72937589, 84.36105834, 13.2931582 ,
        28.63918422, 58.99016787, 96.98997908, 56.54199171,  2.84608165],
       [80.2626346 , 24.06445311, 80.90341437, 39.39820376, 86.4906436 ,
        74.96504263, 56.06778317, 14.50906734

In [120]:
np.random.normal(loc=0,scale=5,size=(5,5))

array([[ 8.13825377,  1.69005848, -5.99634016,  4.31672659, -0.90460151],
       [-3.01960314, -6.15029068,  2.75268748,  3.96403433, -3.11765365],
       [ 2.60288169, -5.72170695,  4.00930516,  0.23283649, -0.93284886],
       [-0.50872936,  4.34443079,  3.7520582 ,  2.64732662,  0.68850605],
       [ 0.38910564,  3.09190131,  1.1624728 ,  3.41275703, -1.55058387]])

In [123]:
np.isnan(a)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [124]:
a>3

array([ True,  True,  True, False,  True,  True,  True, False, False,
       False,  True,  True,  True,  True,  True])

In [125]:
arrr=np.where(a<4)
arrr

(array([3, 7, 8, 9]),)

In [126]:
np.any(a>4)

True

In [128]:
np.all(a>-3)

True

In [132]:
ff=np.array([1,2,3])
np.save('f.npy',ff)
np.save('f',ff)

In [133]:
gg=np.load('f.npy')
gg

array([1, 2, 3])